version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
  backend:
    restart: always
    build:
      context: ./server
      dockerfile: ../.docker/server/Dockerfile
    env_file: ./server/.env
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
  client:
    stdin_open: true
    restart: on-failure
    build:
      context: ./client
      dockerfile: ../.docker/client/Dockerfile
    env_file: ./client/.env
    depends_on:
      - backend
    volumes:
      - ./client:/usr/src/app
    ports:
      - 3000:3000

volumes:
  mongo-volume:
