export const VERIFY_AUTH_SUCCESS = "AUTH/VERIFY_AUTH_SUCCESS";
export const VERIFY_AUTH_FAILURE = "AUTH/VERIFY_AUTH_FAILURE";
export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "AUTH/LOGIN_FAILURE";
export const LOGOUT = "AUTH/LOGOUT";
